// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// doubleSample
double doubleSample(NumericVector prob, IntegerVector numG3, int obs, int nTrial);
RcppExport SEXP LinkageAnalysis_doubleSample(SEXP probSEXP, SEXP numG3SEXP, SEXP obsSEXP, SEXP nTrialSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< NumericVector >::type prob(probSEXP );
        Rcpp::traits::input_parameter< IntegerVector >::type numG3(numG3SEXP );
        Rcpp::traits::input_parameter< int >::type obs(obsSEXP );
        Rcpp::traits::input_parameter< int >::type nTrial(nTrialSEXP );
        double __result = doubleSample(prob, numG3, obs, nTrial);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
